# Site settings
title: Eschelberg
email: magnus@eschelberg.net
description: > # this means to ignore newlines until "baseurl:"
  2003 - 2018
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eschelberg.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

repository: eschelberg/eschelberg.github.io

gems:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji